### ISSUE TITLE
Make pakfront "go get" -able

### ISSUE THREAD

**Issue by AnotherOctopus** [purduerov/X11-Core#4]
It would be really nice if instead of a jank bash script. pakfront could be installed with a single `go get` command. 

Note: Perhaps we should also have a discussion about whether we are using pakfront going forward

**Comment by mattmolo** [comment]
Besides splitting pakfront into its own github repo, there might be a way to setup a seperate registry that it can be pushed to that is accessible with `go get` (Jenkins could potentially push it when it passes checks on a certain branch)
